# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f325334a0b4d50ae45e98d879420ebb2bb1af0b5526c196bbf0dfe3ff551bc45f0b8c7adadc4d656b79d459dc33824e4ef0339ddccf8bd7218c623fafd4d471a

test:
  secret_key_base: 2d55af36937e5920cce981c9a489914a73605de2ece66a0a7f8a33fd1a55d87f54bb05b446bffe9bc71145c7e014a4247b07d9f5aa2764212b8e1054143c6e11

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
